const ADF_FIELDS=['ID_DECLARATION','REFERENCE_DECLARATION','ID_UNIQUE_PARTENAIRE','NOM_FORMATION','DATE_DEBUT_FORMATION','DATE_FIN_FORMATION','MODALITE_DISPENSE','COMPETENCE_TRANSFERABLE','QUALIFICATION_FORMATEUR','FORMATION_CERTIFIANTE','CERTIFICATION_VISEE','DOMAINE_FORMATION','SPECIALITE_FORMATION','NIR','NOM_TITULAIRE','PRESENCE_EMPLOYEUR','SIRET_EMPLOYEUR','REFERENCE_EMPLOYEUR','DATE_DEBUT_VALIDITE','DATE_FIN_VALIDITE'];
const JDR_FIELDS=['ID_DECLARATION','REFERENCE_DECLARATION','ID_UNIQUE_PARTENAIRE','TYPE_JDR','NOM_JDR','NOM_OPTION_SPECIALITE','MODE_OBTENTION','COMPETENCE_TRANSFERABLE','PRESENCE_FORMATION','NOM_FORMATION','DATE_DEBUT_FORMATION','DATE_FIN_FORMATION','MODALITE_DISPENSE','QUALIFICATION_FORMATEUR','FORMATION_CERTIFIANTE','CERTIFICATION_VISEE','DOMAINE_FORMATION','SPECIALITE_FORMATION','NIR','NOM_TITULAIRE','PRESENCE_EMPLOYEUR','SIRET_EMPLOYEUR','REFERENCE_EMPLOYEUR','DATE_DEBUT_VALIDITE','DATE_FIN_VALIDITE','RESULTAT_OBTENU','MENTION_OBTENUE','LIEN_PREUVE','IDENTIFIANT_PREUVE'];
const ADF_REQUIRED=new Set(['ID_DECLARATION','REFERENCE_DECLARATION','ID_UNIQUE_PARTENAIRE','NOM_FORMATION','DATE_DEBUT_FORMATION','DATE_FIN_FORMATION','COMPETENCE_TRANSFERABLE','FORMATION_CERTIFIANTE','NIR','NOM_TITULAIRE','PRESENCE_EMPLOYEUR','DATE_DEBUT_VALIDITE']);
const JDR_REQUIRED=new Set(['ID_DECLARATION','REFERENCE_DECLARATION','ID_UNIQUE_PARTENAIRE','TYPE_JDR','NOM_JDR','COMPETENCE_TRANSFERABLE','NIR','NOM_TITULAIRE','PRESENCE_EMPLOYEUR','DATE_DEBUT_VALIDITE']);
const MAXLEN_COMMON={ID_DECLARATION:255,REFERENCE_DECLARATION:280,ID_UNIQUE_PARTENAIRE:255,NOM_FORMATION:250,MODALITE_DISPENSE:20,COMPETENCE_TRANSFERABLE:70,QUALIFICATION_FORMATEUR:45,FORMATION_CERTIFIANTE:3,CERTIFICATION_VISEE:9,DOMAINE_FORMATION:30,SPECIALITE_FORMATION:15,NIR:13,NOM_TITULAIRE:30,PRESENCE_EMPLOYEUR:3,SIRET_EMPLOYEUR:14,REFERENCE_EMPLOYEUR:255};
const MAXLEN_JDR={...MAXLEN_COMMON,TYPE_JDR:50,NOM_JDR:255,NOM_OPTION_SPECIALITE:255,MODE_OBTENTION:20,PRESENCE_FORMATION:3,RESULTAT_OBTENU:1000,MENTION_OBTENUE:255,LIEN_PREUVE:255,IDENTIFIANT_PREUVE:255};
const ALIASES={
ID_DECLARATION:['id declaration','id_declaration','session id','id session','session'],REFERENCE_DECLARATION:['reference declaration','référence déclaration','reference session','ref declaration','ref session'],ID_UNIQUE_PARTENAIRE:['id unique partenaire','id stagiaire','id participant','identifiant stagiaire','participant id'],NOM_FORMATION:['nom formation','formation','intitule formation','intitulé formation'],DATE_DEBUT_FORMATION:['date debut formation','début formation','date début','debut'],DATE_FIN_FORMATION:['date fin formation','fin formation','date fin','fin'],MODALITE_DISPENSE:['modalite dispense','modalité','modalite','mode'],COMPETENCE_TRANSFERABLE:['competence transferable','compétence transferable','codes rome','code rome','rome'],QUALIFICATION_FORMATEUR:['qualification formateur','formateur'],FORMATION_CERTIFIANTE:['formation certifiante','certifiante'],CERTIFICATION_VISEE:['certification visee','certification visée','code rs','code rncp','certification'],DOMAINE_FORMATION:['domaine formation','formacode'],SPECIALITE_FORMATION:['specialite formation','spécialité formation','nsf'],NIR:['nir','numero securite sociale','numéro sécurité sociale','securite sociale'],NOM_TITULAIRE:['nom titulaire','nom naissance','nom de naissance','nom'],PRESENCE_EMPLOYEUR:['presence employeur','présence employeur','employeur ?','employeur'],SIRET_EMPLOYEUR:['siret employeur','siret'],REFERENCE_EMPLOYEUR:['reference employeur','référence employeur','ref employeur'],DATE_DEBUT_VALIDITE:['date debut validite','début validité','debut validite'],DATE_FIN_VALIDITE:['date fin validite','fin validité','fin validite'],TYPE_JDR:['type jdr','type justificatif','type justificatif reussite'],NOM_JDR:['nom jdr','nom justificatif','justificatif'],NOM_OPTION_SPECIALITE:['nom option specialite','option specialite','option','spécialité jdr'],MODE_OBTENTION:['mode obtention','obtention'],PRESENCE_FORMATION:['presence formation','présence formation','formation ?'],RESULTAT_OBTENU:['resultat obtenu','résultat obtenu','resultat'],MENTION_OBTENUE:['mention obtenue','mention'],LIEN_PREUVE:['lien preuve','preuve url','url preuve'],IDENTIFIANT_PREUVE:['identifiant preuve','id preuve']};
const QUALS=['ENSEIGNANT','FORMATEUR_D_ADULTES_FORMATION_SPECIALISEE','INGENIEUR','PREVENTEUR','PSYCHOLOGUE','RESPONSABLE_QHSE','ANCIEN_PROFESSIONNEL'];
const MODES=['A_DISTANCE','PRESENTIEL','MIXTE'];
const $=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const norm=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
let currentType='ADF',rawRows=[],headers=[],mapping={},issues=[],fileIssues=[],currentFile=null;
const schema=()=>currentType==='ADF'?{fields:ADF_FIELDS,required:ADF_REQUIRED,maxlen:MAXLEN_COMMON}:{fields:JDR_FIELDS,required:JDR_REQUIRED,maxlen:MAXLEN_JDR};
function cell(r,f){const h=mapping[f];return h?String(r[h]??'').trim():''}
function setCell(r,f,v){let h=mapping[f];if(!h){h=f;if(!headers.includes(h))headers.push(h);mapping[f]=h;for(const row of rawRows)if(!(h in row))row[h]='';}r[h]=v}
function listCodes(s){return String(s||'').split('/').map(x=>x.trim()).filter(Boolean)}
function parseDate(s){if(!s)return null;const m=String(s).trim().match(/^(\d{1,2})[\/\-.](\d{1,2})[\/\-.](\d{4})$/);if(m){const d=new Date(+m[3],+m[2]-1,+m[1]);return d.getFullYear()==+m[3]&&d.getMonth()==+m[2]-1&&d.getDate()==+m[1]?d:null}const d=new Date(s);return isNaN(d)?null:d}
function fmtDate(s){const d=parseDate(s);return d?`${String(d.getDate()).padStart(2,'0')}/${String(d.getMonth()+1).padStart(2,'0')}/${d.getFullYear()}`:String(s||'').trim()}
function normalizeYesNo(v){const n=norm(v);if(['oui','yes','y','1','vrai','true'].includes(n))return'OUI';if(['non','no','n','0','faux','false'].includes(n))return'NON';return String(v||'').trim().toUpperCase()}
function normalizeEnum(v,dict){const n=norm(v);return dict[n]||String(v||'').trim().toUpperCase().replace(/[\s-]+/g,'_')}
function normalizeCodes(v){return String(v||'').trim().replace(/[;,]+/g,'/').replace(/\s*\/\s*/g,'/').replace(/\/{2,}/g,'/').replace(/^\/|\/$/g,'')}
function detectField(h){const n=norm(h);let best='',score=0;for(const f of schema().fields){for(const a of [f,...(ALIASES[f]||[])]){const na=norm(a);let sc=n===na?100:(n.includes(na)||na.includes(n)?60:0);if(sc>score){score=sc;best=f}}}return score>=60?best:''}
function profileKey(){return 'pcl_profiles_v3'}
function loadProfiles(){try{return JSON.parse(localStorage.getItem(profileKey())||'[]')}catch{return[]}}
function saveProfiles(p){localStorage.setItem(profileKey(),JSON.stringify(p))}
function refreshProfiles(selected=''){const ps=loadProfiles().filter(p=>p.type===currentType);$('#profileSelect').innerHTML='<option value="">Auto-détection</option>'+ps.map(p=>`<option value="${esc(p.name)}" ${p.name===selected?'selected':''}>${esc(p.name)}</option>`).join('');$('#deleteProfile').disabled=!selected}
function autoMap(){mapping={};headers.forEach(h=>{const f=detectField(h);if(f&&!mapping[f])mapping[f]=h});const ps=loadProfiles().filter(p=>p.type===currentType);const matched=ps.find(p=>Object.values(p.mapping).filter(Boolean).every(h=>headers.includes(h)));if(matched){mapping={...mapping,...matched.mapping};refreshProfiles(matched.name);$('#deleteProfile').disabled=false}else refreshProfiles();renderMapping()}
function renderMapping(){const {fields,required}=schema(),box=$('#mapping');if(!headers.length){box.innerHTML='<div class="empty">Les colonnes seront associées automatiquement après l’import.</div>';updateMapCount();return}box.innerHTML=fields.map(f=>`<div class="maprow"><code>${f}${required.has(f)?' *':''}</code><span class="arrow">→</span><select data-field="${f}"><option value="">— non associé —</option>${headers.map(h=>`<option value="${esc(h)}" ${mapping[f]===h?'selected':''}>${esc(h)}</option>`).join('')}</select></div>`).join('');box.querySelectorAll('select').forEach(s=>s.onchange=()=>{mapping[s.dataset.field]=s.value;updateMapCount();validateAll()});updateMapCount();$('#validate').disabled=false;$('#autofix').disabled=false;$('#genids').disabled=false;$('#saveProfile').disabled=false}
function updateMapCount(){const fields=schema().fields,c=fields.filter(f=>mapping[f]).length;$('#mapCount').textContent=`${c}/${fields.length}`}
function addIssue(row,field,level,msg){issues.push({row,field,level,msg})}
function validateFileMeta(file){fileIssues=[];if(!file)return;const n=file.name||'';if(n.length>200)fileIssues.push({level:'error',msg:'Le nom du fichier dépasse 200 caractères.'});if(/[@<>;"\/\\|?*%]/.test(n))fileIssues.push({level:'warning',msg:'Le nom source contient un caractère refusé par le portail ; l’export généré utilisera un nom sûr.'});if(file.size>200*1024*1024)fileIssues.push({level:'error',msg:'Le fichier dépasse 200 Mo.'});const el=$('#filecheck');el.classList.remove('hidden','ok','bad');if(fileIssues.some(x=>x.level==='error')){el.classList.add('bad');el.textContent=fileIssues.map(x=>x.msg).join(' ')}else{el.classList.add('ok');el.textContent=fileIssues.length?'Source lisible. '+fileIssues.map(x=>x.msg).join(' '):'Source lisible. L’export final respectera le format CSV UTF‑8 et le séparateur |.'}}
function validateCommonRow(r,i,opts={trainingRequired:true,trainingForbidden:false}){const {fields,maxlen}=schema(),today=new Date();today.setHours(23,59,59,999);for(const f of fields){const v=cell(r,f);if(v.includes('|')||/[\r\n]/.test(v))addIssue(i+2,f,'error','Caractère interdit pour un export séparé par |');if(v&&maxlen[f]&&v.length>maxlen[f])addIssue(i+2,f,'error',`Longueur maximale : ${maxlen[f]} caractères`)}
 const train=['NOM_FORMATION','DATE_DEBUT_FORMATION','DATE_FIN_FORMATION','MODALITE_DISPENSE','QUALIFICATION_FORMATEUR','FORMATION_CERTIFIANTE','CERTIFICATION_VISEE','DOMAINE_FORMATION','SPECIALITE_FORMATION'];
 if(opts.trainingForbidden){for(const f of train)if(cell(r,f))addIssue(i+2,f,'error','Doit rester vide lorsque PRESENCE_FORMATION=NON')}
 let d1=dateVal(cell(r,'DATE_DEBUT_FORMATION')),d2=dateVal(cell(r,'DATE_FIN_FORMATION')),dv1=dateVal(cell(r,'DATE_DEBUT_VALIDITE')),dv2=cell(r,'DATE_FIN_VALIDITE')?dateVal(cell(r,'DATE_FIN_VALIDITE')):null;
 if(opts.trainingRequired){for(const f of ['DATE_DEBUT_FORMATION','DATE_FIN_FORMATION'])if(cell(r,f)&&!dateVal(cell(r,f)))addIssue(i+2,f,'error','Date attendue au format jj/mm/aaaa');if(d1&&d1>today)addIssue(i+2,'DATE_DEBUT_FORMATION','error','La date de début ne doit pas être future');if(d2&&d2>today)addIssue(i+2,'DATE_FIN_FORMATION','error','La date de fin ne doit pas être future');if(d1&&d2&&d2<d1)addIssue(i+2,'DATE_FIN_FORMATION','error','La date de fin doit être ≥ à la date de début')}
 if(cell(r,'DATE_DEBUT_VALIDITE')&&!dv1)addIssue(i+2,'DATE_DEBUT_VALIDITE','error','Date attendue au format jj/mm/aaaa');if(cell(r,'DATE_FIN_VALIDITE')&&!dv2)addIssue(i+2,'DATE_FIN_VALIDITE','error','Date attendue au format jj/mm/aaaa');if(dv1&&d2&&opts.trainingRequired&&dv1<d2)addIssue(i+2,'DATE_DEBUT_VALIDITE','error','La validité doit débuter au plus tôt à la fin de la formation');if(dv1&&dv2&&dv2<dv1)addIssue(i+2,'DATE_FIN_VALIDITE','error','La fin de validité doit être ≥ au début de validité');
 const mode=cell(r,'MODALITE_DISPENSE');if(mode&&opts.trainingRequired&&!MODES.includes(mode))addIssue(i+2,'MODALITE_DISPENSE','error','Valeurs admises : A_DISTANCE, PRESENTIEL, MIXTE');const q=cell(r,'QUALIFICATION_FORMATEUR');if(q&&opts.trainingRequired&&!QUALS.includes(q))addIssue(i+2,'QUALIFICATION_FORMATEUR','error','Qualification formateur non reconnue');
 if(opts.trainingRequired){const cert=cell(r,'FORMATION_CERTIFIANTE'),cv=cell(r,'CERTIFICATION_VISEE'),dom=listCodes(cell(r,'DOMAINE_FORMATION')),spe=listCodes(cell(r,'SPECIALITE_FORMATION'));if(cert&&!['OUI','NON'].includes(cert))addIssue(i+2,'FORMATION_CERTIFIANTE','error','Valeur attendue : OUI ou NON');if(cert==='OUI'){if(!cv)addIssue(i+2,'CERTIFICATION_VISEE','error','Obligatoire pour une formation certifiante');if(dom.length)addIssue(i+2,'DOMAINE_FORMATION','error','Doit rester vide si la formation est certifiante');if(spe.length)addIssue(i+2,'SPECIALITE_FORMATION','error','Doit rester vide si la formation est certifiante')}if(cert==='NON'){if(cv)addIssue(i+2,'CERTIFICATION_VISEE','error','Doit rester vide si la formation n’est pas certifiante');if(dom.length<1||dom.length>5)addIssue(i+2,'DOMAINE_FORMATION','error','1 à 5 Formacodes requis');if(spe.length<1||spe.length>3)addIssue(i+2,'SPECIALITE_FORMATION','error','1 à 3 codes NSF requis')}}
 const rome=listCodes(cell(r,'COMPETENCE_TRANSFERABLE'));if(rome.length<3||rome.length>10)addIssue(i+2,'COMPETENCE_TRANSFERABLE','error','3 à 10 codes ROME requis, séparés par /');const nir=cell(r,'NIR').replace(/\s/g,'');if(nir&&!/^\d{13}$/.test(nir))addIssue(i+2,'NIR','error','Le NIR doit contenir exactement 13 chiffres');const pe=cell(r,'PRESENCE_EMPLOYEUR');if(pe&&!['OUI','NON'].includes(pe))addIssue(i+2,'PRESENCE_EMPLOYEUR','error','Valeur attendue : OUI ou NON');const siret=cell(r,'SIRET_EMPLOYEUR').replace(/\s/g,'');if(pe==='OUI'&&!/^\d{14}$/.test(siret))addIssue(i+2,'SIRET_EMPLOYEUR','error','SIRET obligatoire sur 14 chiffres si PRESENCE_EMPLOYEUR=OUI');if(pe==='NON'&&siret)addIssue(i+2,'SIRET_EMPLOYEUR','error','Doit rester vide si PRESENCE_EMPLOYEUR=NON');if(pe==='NON'&&cell(r,'REFERENCE_EMPLOYEUR'))addIssue(i+2,'REFERENCE_EMPLOYEUR','error','Doit rester vide si PRESENCE_EMPLOYEUR=NON')}
function dateVal(s){const d=parseDate(s);return d&&!isNaN(d)?d:null}
function validateAll(){issues=[];for(const x of fileIssues)addIssue('Fichier','—',x.level,x.msg);const {required}=schema(),ids=new Map(),groups=new Map();rawRows.forEach((r,i)=>{for(const f of required)if(!mapping[f]||!cell(r,f))addIssue(i+2,f,'error','Valeur obligatoire manquante');if(currentType==='ADF'){validateCommonRow(r,i,{trainingRequired:true});validateGroup(r,i,groups,['REFERENCE_DECLARATION','NOM_FORMATION','DATE_DEBUT_FORMATION','DATE_FIN_FORMATION','MODALITE_DISPENSE','COMPETENCE_TRANSFERABLE','QUALIFICATION_FORMATEUR','FORMATION_CERTIFIANTE','CERTIFICATION_VISEE','DOMAINE_FORMATION','SPECIALITE_FORMATION'])}else{const type=cell(r,'TYPE_JDR');if(type&&!['DIPLOME','TITRE','HABILITATION','CERTIFICAT'].includes(type))addIssue(i+2,'TYPE_JDR','error','Valeurs admises : DIPLOME, TITRE, HABILITATION, CERTIFICAT');const mo=cell(r,'MODE_OBTENTION');if(mo&&!['PAR_ADMISSION','PAR_SCORING'].includes(mo))addIssue(i+2,'MODE_OBTENTION','error','Valeurs admises : PAR_ADMISSION ou PAR_SCORING');const pf=cell(r,'PRESENCE_FORMATION');if(pf&&!['OUI','NON'].includes(pf))addIssue(i+2,'PRESENCE_FORMATION','error','Valeur attendue : OUI, NON ou vide');const hasTraining=pf==='OUI';if(hasTraining){for(const f of ['NOM_FORMATION','DATE_DEBUT_FORMATION','DATE_FIN_FORMATION','FORMATION_CERTIFIANTE'])if(!cell(r,f))addIssue(i+2,f,'error','Obligatoire lorsque PRESENCE_FORMATION=OUI');validateCommonRow(r,i,{trainingRequired:true})}else validateCommonRow(r,i,{trainingRequired:false,trainingForbidden:true});const link=cell(r,'LIEN_PREUVE');if(link&&!/^https?:\/\//i.test(link))addIssue(i+2,'LIEN_PREUVE','error','Le lien de preuve doit commencer par http:// ou https://');validateGroup(r,i,groups,['REFERENCE_DECLARATION','TYPE_JDR','NOM_JDR','NOM_OPTION_SPECIALITE','MODE_OBTENTION','COMPETENCE_TRANSFERABLE','PRESENCE_FORMATION','NOM_FORMATION','DATE_DEBUT_FORMATION','DATE_FIN_FORMATION','MODALITE_DISPENSE','QUALIFICATION_FORMATEUR','FORMATION_CERTIFIANTE','CERTIFICATION_VISEE','DOMAINE_FORMATION','SPECIALITE_FORMATION'])}
 const uid=cell(r,'ID_UNIQUE_PARTENAIRE');if(uid){if(ids.has(uid))addIssue(i+2,'ID_UNIQUE_PARTENAIRE','error',`Identifiant déjà utilisé ligne ${ids.get(uid)}`);else ids.set(uid,i+2)}});renderIssues();return issues.filter(x=>x.level==='error').length===0}
function validateGroup(r,i,groups,common){const gid=cell(r,'ID_DECLARATION');if(!gid)return;const sig=common.map(f=>cell(r,f)).join('\u0001');if(!groups.has(gid))groups.set(gid,{sig,count:1,row:i+2});else{const g=groups.get(gid);g.count++;if(g.sig!==sig)addIssue(i+2,'ID_DECLARATION','error',`Les données de la déclaration diffèrent de la ligne ${g.row}`);if(g.count>500)addIssue(i+2,'ID_DECLARATION','error','Une déclaration ne peut pas dépasser 500 titulaires')}}
function renderIssues(){const errors=issues.filter(x=>x.level==='error'),warnings=issues.filter(x=>x.level==='warning');$('#sRows').textContent=rawRows.length;$('#sErrors').textContent=errors.length;$('#sWarnings').textContent=warnings.length;const badRows=new Set(errors.filter(x=>typeof x.row==='number').map(x=>x.row));$('#sReady').textContent=Math.max(0,rawRows.length-badRows.size);const b=$('#statusBadge');if(!rawRows.length){b.className='badge warn';b.textContent='En attente'}else if(errors.length){b.className='badge err';b.textContent=`${errors.length} erreur${errors.length>1?'s':''}`}else{b.className='badge ok';b.textContent='Prêt à exporter'}if(!issues.length){$('#issuesBody').innerHTML=rawRows.length?`<div class="empty"><strong>Pré-contrôle réussi.</strong><br>Le fichier ${currentType} peut être exporté pour dépôt sur le portail officiel.</div>`:'<div class="empty">Chargez un fichier pour lancer les contrôles.</div>'}else{$('#issuesBody').innerHTML=`<table class="issue-table"><thead><tr><th>Niveau</th><th>Ligne</th><th>Champ</th><th>Message</th></tr></thead><tbody>${issues.slice(0,250).map(x=>`<tr><td class="level ${x.level}">${x.level==='error'?'Erreur':'Alerte'}</td><td>${x.row}</td><td><code>${esc(x.field)}</code></td><td>${esc(x.msg)}</td></tr>`).join('')}</tbody></table>${issues.length>250?'<div class="notice">Affichage limité aux 250 premiers problèmes.</div>':''}`}$('#download').disabled=errors.length>0||!rawRows.length;$('#report').disabled=!issues.length}
